# Generated by Django 4.2.11 on 2024-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_person_delete_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(default='No Description', max_length=500),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='2/static/images/blank-car-Photoroom.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Mystery', max_length=100),
        ),
    ]
