# Generated by Django 4.2.11 on 2024-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_person_description_person_image_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(default='No Description', max_length=2000),
        ),
    ]
