# Generated by Django 4.2.11 on 2024-03-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car', models.CharField(choices=[('F', 'Ferrari'), ('L', 'Lamborghini'), ('M', 'McLaren'), ('A', 'Audi')], default='F', max_length=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
